// Code generated by protoc-gen-go. DO NOT EDIT.
// source: groupcache.proto

package groupcachepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupcache_23d89e66d2af4cdc, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	MinuteQps            float64  `protobuf:"fixed64,2,opt,name=minute_qps,json=minuteQps,proto3" json:"minute_qps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupcache_23d89e66d2af4cdc, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetResponse) GetMinuteQps() float64 {
	if m != nil {
		return m.MinuteQps
	}
	return 0
}

type PutRequest struct {
	Group                string             `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key                  string             `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte             `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Ttl                  *duration.Duration `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupcache_23d89e66d2af4cdc, []int{2}
}
func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (dst *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(dst, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutRequest) GetTtl() *duration.Duration {
	if m != nil {
		return m.Ttl
	}
	return nil
}

type PutResponse struct {
	MinuteQps            float64  `protobuf:"fixed64,1,opt,name=minute_qps,json=minuteQps,proto3" json:"minute_qps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_groupcache_23d89e66d2af4cdc, []int{3}
}
func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (dst *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(dst, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetMinuteQps() float64 {
	if m != nil {
		return m.MinuteQps
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "groupcachepb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "groupcachepb.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "groupcachepb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "groupcachepb.PutResponse")
}

func init() { proto.RegisterFile("groupcache.proto", fileDescriptor_groupcache_23d89e66d2af4cdc) }

var fileDescriptor_groupcache_23d89e66d2af4cdc = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0x1b, 0x57, 0x85, 0xce, 0xf6, 0x50, 0x82, 0x87, 0x6d, 0x41, 0x29, 0x39, 0x15, 0x94,
	0x14, 0xaa, 0x47, 0x4f, 0x2a, 0xec, 0xb5, 0xe6, 0x05, 0x64, 0xb7, 0x8e, 0x6b, 0x71, 0xdd, 0xa4,
	0x9b, 0x44, 0xf1, 0x0d, 0x7c, 0x6c, 0xc9, 0xa4, 0xb2, 0x6b, 0xf5, 0xe2, 0x2d, 0x99, 0x99, 0x1f,
	0xff, 0x0f, 0x18, 0x57, 0xad, 0xf6, 0x66, 0x5d, 0xac, 0x9f, 0x51, 0x9a, 0x56, 0x3b, 0xcd, 0x47,
	0xdd, 0xc4, 0x94, 0xd3, 0xb3, 0x4a, 0xeb, 0xaa, 0xc6, 0x05, 0xed, 0x4a, 0xff, 0xb4, 0x78, 0xf4,
	0x6d, 0xe1, 0x36, 0xba, 0x89, 0xd7, 0xe2, 0x0a, 0x20, 0x47, 0xa7, 0x70, 0xeb, 0xd1, 0x3a, 0x7e,
	0x02, 0x47, 0x44, 0x67, 0x6c, 0xc6, 0xe6, 0x43, 0x15, 0x3f, 0x7c, 0x0c, 0xc9, 0x0b, 0x7e, 0x64,
	0x07, 0x34, 0x0b, 0x4f, 0x71, 0x03, 0x29, 0x51, 0xd6, 0xe8, 0xc6, 0x62, 0xc0, 0xde, 0x8a, 0xda,
	0x23, 0x61, 0x23, 0x15, 0x3f, 0xfc, 0x14, 0xe0, 0x75, 0xd3, 0x78, 0x87, 0x0f, 0x5b, 0x63, 0x89,
	0x66, 0x6a, 0x18, 0x27, 0xf7, 0xc6, 0x8a, 0x77, 0x80, 0x95, 0xff, 0xaf, 0x72, 0x27, 0x95, 0xf4,
	0xa5, 0xce, 0x21, 0x71, 0xae, 0xce, 0x0e, 0x67, 0x6c, 0x9e, 0x2e, 0x27, 0x32, 0x66, 0x96, 0xdf,
	0x99, 0xe5, 0xdd, 0x2e, 0xb3, 0x0a, 0x57, 0xe2, 0x02, 0x52, 0x12, 0xde, 0x99, 0xff, 0x69, 0x93,
	0xed, 0xd9, 0x5c, 0x7e, 0x32, 0x80, 0x3c, 0x98, 0xb9, 0x0d, 0x8d, 0xf2, 0x6b, 0x48, 0x72, 0x74,
	0x3c, 0x93, 0xfd, 0x96, 0x65, 0x57, 0xe1, 0x74, 0xf2, 0xc7, 0x26, 0x2a, 0x89, 0x41, 0xa0, 0x57,
	0xfe, 0x17, 0xdd, 0xd5, 0xb0, 0x4f, 0xf7, 0x7c, 0x8a, 0x41, 0x79, 0x4c, 0x81, 0x2e, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x0a, 0xed, 0x44, 0x7f, 0xf4, 0x01, 0x00, 0x00,
}
