// Code generated by protoc-gen-go. DO NOT EDIT.
// source: groupcache.proto

package groupcachepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba3e029bfa16198, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                []byte               `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	MinuteQps            float64              `protobuf:"fixed64,2,opt,name=minute_qps,json=minuteQps,proto3" json:"minute_qps,omitempty"`
	Ttl                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba3e029bfa16198, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetResponse) GetMinuteQps() float64 {
	if m != nil {
		return m.MinuteQps
	}
	return 0
}

func (m *GetResponse) GetTtl() *timestamp.Timestamp {
	if m != nil {
		return m.Ttl
	}
	return nil
}

type ContainRequest struct {
	Group                string   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainRequest) Reset()         { *m = ContainRequest{} }
func (m *ContainRequest) String() string { return proto.CompactTextString(m) }
func (*ContainRequest) ProtoMessage()    {}
func (*ContainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba3e029bfa16198, []int{2}
}

func (m *ContainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainRequest.Unmarshal(m, b)
}
func (m *ContainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainRequest.Marshal(b, m, deterministic)
}
func (m *ContainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainRequest.Merge(m, src)
}
func (m *ContainRequest) XXX_Size() int {
	return xxx_messageInfo_ContainRequest.Size(m)
}
func (m *ContainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainRequest proto.InternalMessageInfo

func (m *ContainRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *ContainRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ContainResponse struct {
	MinuteQps            float64              `protobuf:"fixed64,1,opt,name=minute_qps,json=minuteQps,proto3" json:"minute_qps,omitempty"`
	Exists               bool                 `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	Ttl                  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Length               int64                `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ContainResponse) Reset()         { *m = ContainResponse{} }
func (m *ContainResponse) String() string { return proto.CompactTextString(m) }
func (*ContainResponse) ProtoMessage()    {}
func (*ContainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba3e029bfa16198, []int{3}
}

func (m *ContainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainResponse.Unmarshal(m, b)
}
func (m *ContainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainResponse.Marshal(b, m, deterministic)
}
func (m *ContainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainResponse.Merge(m, src)
}
func (m *ContainResponse) XXX_Size() int {
	return xxx_messageInfo_ContainResponse.Size(m)
}
func (m *ContainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainResponse proto.InternalMessageInfo

func (m *ContainResponse) GetMinuteQps() float64 {
	if m != nil {
		return m.MinuteQps
	}
	return 0
}

func (m *ContainResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *ContainResponse) GetTtl() *timestamp.Timestamp {
	if m != nil {
		return m.Ttl
	}
	return nil
}

func (m *ContainResponse) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

type PutRequest struct {
	Group                string               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key                  string               `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte               `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Ttl                  *timestamp.Timestamp `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba3e029bfa16198, []int{4}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutRequest) GetTtl() *timestamp.Timestamp {
	if m != nil {
		return m.Ttl
	}
	return nil
}

type PutResponse struct {
	MinuteQps            float64  `protobuf:"fixed64,1,opt,name=minute_qps,json=minuteQps,proto3" json:"minute_qps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aba3e029bfa16198, []int{5}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetMinuteQps() float64 {
	if m != nil {
		return m.MinuteQps
	}
	return 0
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "groupcachepb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "groupcachepb.GetResponse")
	proto.RegisterType((*ContainRequest)(nil), "groupcachepb.ContainRequest")
	proto.RegisterType((*ContainResponse)(nil), "groupcachepb.ContainResponse")
	proto.RegisterType((*PutRequest)(nil), "groupcachepb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "groupcachepb.PutResponse")
}

func init() { proto.RegisterFile("groupcache.proto", fileDescriptor_aba3e029bfa16198) }

var fileDescriptor_aba3e029bfa16198 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0x99, 0x3b, 0x5c, 0xee, 0xe5, 0x40, 0x94, 0x4c, 0x8c, 0xa9, 0x8d, 0x44, 0xd2, 0x15,
	0x0b, 0x52, 0x12, 0x74, 0xe1, 0x82, 0x1d, 0x0b, 0x5c, 0xe2, 0xc4, 0xbd, 0x29, 0xe4, 0x58, 0x1a,
	0x4b, 0x67, 0x60, 0x66, 0x0c, 0xbe, 0x84, 0x0f, 0xe7, 0x13, 0x99, 0xce, 0x14, 0x0a, 0xa8, 0x09,
	0xec, 0xfa, 0x9f, 0x73, 0xfe, 0x99, 0xaf, 0xff, 0x1c, 0x68, 0xc5, 0x2b, 0x61, 0xe4, 0x2c, 0x9a,
	0xcd, 0x31, 0x94, 0x2b, 0xa1, 0x05, 0x6b, 0x96, 0x15, 0x39, 0xf5, 0x6f, 0x62, 0x21, 0xe2, 0x14,
	0xfb, 0xb6, 0x37, 0x35, 0x2f, 0x7d, 0x9d, 0x2c, 0x50, 0xe9, 0x68, 0x21, 0xdd, 0x78, 0x70, 0x07,
	0x30, 0x46, 0xcd, 0x71, 0x69, 0x50, 0x69, 0x76, 0x01, 0x7f, 0xad, 0xdd, 0x23, 0x1d, 0xd2, 0xad,
	0x73, 0x27, 0x58, 0x0b, 0xe8, 0x2b, 0xbe, 0x7b, 0x7f, 0x6c, 0x2d, 0xff, 0x0c, 0x24, 0x34, 0xac,
	0x4b, 0x49, 0x91, 0x29, 0xcc, 0x6d, 0x6f, 0x51, 0x6a, 0xd0, 0xda, 0x9a, 0xdc, 0x09, 0xd6, 0x06,
	0x58, 0x24, 0x99, 0xd1, 0xf8, 0xbc, 0x94, 0xca, 0xba, 0x09, 0xaf, 0xbb, 0xca, 0xa3, 0x54, 0xac,
	0x07, 0x54, 0xeb, 0xd4, 0xa3, 0x1d, 0xd2, 0x6d, 0x0c, 0xfc, 0xd0, 0x81, 0x86, 0x1b, 0xd0, 0xf0,
	0x69, 0x03, 0xca, 0xf3, 0xb1, 0xe0, 0x1e, 0xce, 0x46, 0x22, 0xd3, 0x51, 0x92, 0x9d, 0xca, 0xfa,
	0x41, 0xe0, 0x7c, 0x6b, 0x2d, 0x80, 0xf7, 0xd1, 0xc8, 0x21, 0xda, 0x25, 0xd4, 0x70, 0x9d, 0x28,
	0xed, 0xa8, 0xff, 0xf3, 0x42, 0x9d, 0x86, 0x9c, 0x9f, 0x92, 0x62, 0x16, 0xeb, 0xb9, 0x57, 0xed,
	0x90, 0x2e, 0xe5, 0x85, 0x0a, 0xd6, 0x00, 0x13, 0x73, 0x6a, 0xe4, 0x65, 0xc6, 0x74, 0x37, 0xe3,
	0x82, 0xa8, 0x7a, 0x5c, 0x88, 0x3d, 0x68, 0xd8, 0x9b, 0x8f, 0x4a, 0x61, 0xf0, 0x49, 0x00, 0xc6,
	0x39, 0xcd, 0x28, 0x5f, 0x26, 0x36, 0x04, 0x3a, 0x46, 0xcd, 0xbc, 0x70, 0x77, 0xc1, 0xc2, 0x72,
	0x79, 0xfc, 0xab, 0x1f, 0x3a, 0xee, 0xa6, 0xa0, 0xc2, 0x1e, 0xe0, 0x5f, 0xf1, 0x08, 0xec, 0x7a,
	0x7f, 0x6e, 0xff, 0x59, 0xfd, 0xf6, 0x2f, 0xdd, 0xed, 0x49, 0x43, 0xa0, 0x13, 0xf3, 0x8d, 0xa3,
	0x4c, 0xf4, 0x90, 0x63, 0xe7, 0x8f, 0x83, 0xca, 0xb4, 0x66, 0xb3, 0xb9, 0xfd, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x30, 0x20, 0xbf, 0x1b, 0x39, 0x03, 0x00, 0x00,
}
